name: build aria2

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
      - name: Setup upterm session
        uses: mxschmitt/action-tmate@v3
      - name: install homebrew
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install aria2
        run: brew update && brew install aria2
      - name: Upload a Build Artifact 
        uses: actions/upload-artifact@v4.2.0
        with:
          name: aria2c-mac
          path: /usr/local/bin/aria2c
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: install requirement
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf autopoint libtool pkg-config g++ zlib1g-dev ca-certificates gcc libxml2-dev
      - name: openssl
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          tar zxvf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./Configure linux-x86_64 no-asm shared
          sudo make -s -j2 && sudo make install
      - name: c-ares
        run: |
          git clone https://github.com/c-ares/c-ares.git
          cd c-ares
          autoreconf -fi
          ./configure
          sudo make -s && sudo make install
      - name: sqlite
        run: |
          wget https://www.sqlite.org/2024/sqlite-autoconf-3450000.tar.gz
          tar zxvf sqlite-autoconf-3450000.tar.gz
          cd sqlite-autoconf-3450000
          ./configure
          sudo make -s && sudo make install
      - name: libuv
        run: |
          wget https://dist.libuv.org/dist/v1.47.0/libuv-v1.47.0.tar.gz
          tar zxvf libuv-v1.47.0.tar.gz
          cd libuv-v1.47.0
          sudo ./autogen.sh
          ./configure
          sudo make -s && sudo make install
      - name: jemalloc
        run: |
          git clone https://github.com/jemalloc/jemalloc.git
          cd jemalloc
          sudo ./autogen.sh
          sudo make -s && sudo make install
      - name: build aria2
        run: |
          sudo ldconfig
          git clone https://github.com/aria2/aria2.git
          cd aria2
          autoreconf -i
          ./configure --enable-static=yes --with-libuv --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt' --with-jemalloc ARIA2_STATIC=yes
          sudo make -s -j2
          sudo strip src/aria2c
      - name: Upload a Build Artifact 
        uses: actions/upload-artifact@v4.2.0
        with:
          path: aria2/src/aria2c
