name: build aria2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: install requirement
        run: |
          sudo cat /proc/cpuinfo
          sudo cat /proc/meminfo
          sudo apt-get update
          sudo apt-get install autoconf autopoint libtool pkg-config g++ zlib1g-dev
      - name: openssl
        run: |
          git clone https://github.com/openssl/openssl.git
          cd openssl
          ./Configure linux-x86_64 no-asm shared
          sudo make -s && make install
      - name: c-ares
        run: |
          git clone https://github.com/c-ares/c-ares.git
          cd c-ares
          ./configure
          sudo make -s && make install
          
          
          
          
          
          
