name: build aria2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: install requirement
        run: |
          sudo apt-get update
          sudo apt-get install autoconf autopoint libtool pkg-config g++ zlib1g-dev
      - name: openssl
        run: |
          git clone https://github.com/openssl/openssl.git
          cd openssl
          ./Configure linux-x86_64 no-asm shared
          sudo make -s && sudo make install
      - name: c-ares
        run: |
          wget https://c-ares.haxx.se/download/c-ares-1.16.1.tar.gz
          tar zxvf c-ares-1.16.1.tar.gz
          cd c-ares-1.16.1
          ./configure
          sudo make -s && sudo make install
      - name: libxml2
        run: |
          git clone https://gitlab.gnome.org/GNOME/libxml2.git
          cd libxml2
          ./autogen.sh
          ./configure
          sudo make -s && sudo make install 
      - name: sqlite
        run: |
          wget https://www.sqlite.org/2020/sqlite-autoconf-3330000.tar.gz
          tar zxvf sqlite-autoconf-3330000.tar.gz
          cd sqlite-autoconf-3330000
          ./configure
          sudo make -s && sudo make install
      - name: libuv
        run: |
          wget https://dist.libuv.org/dist/v1.40.0/libuv-v1.40.0.tar.gz
          tar zxvf libuv-v1.40.0.tar.gz
          cd libuv-v1.40.0
          sudo ./autogen.sh
          ./configure
          sudo make -s && sudo make install
      - name: jemalloc
        run: |
          git clone https://github.com/jemalloc/jemalloc.git
          cd jemalloc
          sudo ./autogen.sh
          sudo make -s && sudo make install
      - name: build aria2
        run: |
          sudo ldconfig
          git clone https://github.com/aria2/aria2.git
          cd aria2
          autoreconf -i
          ./configure --enable-static=yes --with-libuv --with-jemalloc ARIA2_STATIC=yes
          sudo make -s
          pwd
          ls     
      - name: Upload a Build Artifact 
        uses: actions/upload-artifact@v2.2.0
        with:
          path: aria2/src/aria2c
